
version: '3.8'

services:
  pgdatabase:
    image: postgres:13 
    container_name: postgres_container 
    restart: always 
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ny_taxi_db

    volumes:
      - './ny_taxi_postgres_data:/var/lib/postgresql/data:rw'
    ports:
      - "5433:5432"

  pgadmin:
    image: dpage/pgadmin4 
    container_name: pgadmin_container
    restart: always 
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=password 
    depends_on:
      - pgdatabase   
    ports:
      - "8080:80" 

networks:
  default: 
    name: my_network 

volumes:
  postgres_data: 
 